config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  # API ROUTES ---------------------------------------------------

  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      post '/login',              to: 'sessions#create'
      post '/logout',             to: 'sessions#destroy'
      post '/reset_password',     to: 'users#reset_password'

      resources :users, only: [:index, :show, :update] do
        resources :tasks, only: [:index, :show, :create, :update] do
          post '/complete', to: 'tasks#complete', on: :member
          post '/incomplete', to: 'tasks#incomplete', on: :member
        end
        resources :points_transactions, only: [:index, :create]
      end

      resources :approvals, only: [:index] do
        post '/approve', to: 'approvals#approve', on: :member
      end

      resources :dues, only: [:index]
      resources :dues_transactions, only: [:index, :create]

      resources :event_invites, only: [:index] do
        post '/rsvp', to: 'event_invites#rsvp', on: :member
        post '/check_in', to: 'event_invites#check_in', on: :member
      end

      resources :meeting_notes, only: [:index, :show, :create]

      resources :channels, only: [:index] do
        resources :messages, only: [:index, :create]
      end

      resources :direct_messages, only: [:index, :create] do
        resources :message_groups_users, only: [:index, :create, :update]
        resources :messages, only: [:index, :create]
      end

      resources :budgets, only: [:index] do
        resources :budget_transactions, only: [:index, :create]
      end

      resources :user_grades, only: [:index, :show, :create]
    end
  end


  # WEB APP ROUTES ---------------------------------------------------

  root 'static_pages#index'
  get 'my_flow', to: 'users#my_flow'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }

  resources :users, only: [:index, :show] do
    collection do
      get 'my_info', action: :my_info
      put 'update_my_avatar', action: :update_my_avatar
      put 'update_my_info', action: :update_my_info
    end
  end

  resources :user_grades, only: [:index, :create, :destroy]

  resources :points_transactions, only: [:index, :create]

  resources :tasks, only: [:index, :create] do
    post '/complete', to: 'tasks#complete', on: :member
  end

  resources :calendar, only: [:index, :show, :new, :create] do
    member do
      post 'rsvp', action: :rsvp
      post 'invite', action: :invite
    end

    collection do
      post 'events', action: :events
      post 'event', action: :create_event
    end
  end

  resources :forms, only: [:index] do
    resources :form_submissions, only: [:index, :create]
  end

  resources :teams, only: [:index, :show, :create, :update, :destroy] do
    put 'update_organization_image', action: :update_organization_image, on: :member
    resources :organization_user_roles, only: [:create, :destroy]
  end

  resources :meeting_notes, only: [:index, :show]

  resources :channels, only: [:index, :show, :create, :destroy] do
    resources :messages, only: [:create]
  end

  resources :direct_messages, only: [:index, :show, :create, :destroy] do
    resources :messages, only: [:create]
  end

  resources :dues, only: [:index]
  resources :dues_transactions, only: [:create]

  resources :budgets, only: [:index, :show] do
    resources :budget_transactions, only: [:create]
  end

  resources :organization_links, only: [:index, :create, :destroy]

  resources :birthdays, only: [:index]

  resources :approvals, only: [:index] do
    post 'approve', action: :approve, on: :member
  end

  get 'st_page/:page', to: 'static_pages#page'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
		unless user_signed_in?
			redirect_to new_user_session_path
		else
			render :home, layout: false
		end
	end

	def home
		render :home, layout: false
	end



	def page

		p params[:page]

		render params[:page]

	end















end

app/views/static_pages/_menu_item.html.haml
.menu-item.hovered-icon
  = link_to menu_item_path, class: 'item-container' do
    .item-icon
      = svg_icon(svg_name)
      - if num_count > 0
        .info-red-dot
          = num_count
    %br
    %span.text
      - if title.length > 14
        = raw title.sub(' ', '<br/>')
      - else
        = title

app/views/static_pages/chapter_performance.html.haml
.page-container
  = svg_icon 'chapter_performance'

app/views/static_pages/dues.html.haml
.page-container
  = svg_icon 'dues'

app/views/static_pages/home.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    %title Rowflow
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.home
    %header.home-header
      .content
        .logo
          = svg_icon 'logo'
          -#= image_tag 'logo.png', height: 72

        .user-box
          .user-text-content
            .welcome
              = current_user.full_name
            .info
              You have 5 unread items
          .user-avatar
            = link_to my_info_users_path do
              = image_tag current_user.image.url, height: 50
            %span.info-red-dot
              5

    .home-menu-container
      .menu-row
        = home_menu_item my_flow_path, 'my_flow', 'MyFlow', 0
        = home_menu_item tasks_path, 'tasks', 'Tasks', 0
        = home_menu_item calendar_index_path, 'calendar', 'Calendar', 0
        = home_menu_item users_path, 'directory', 'Directory', 0
        = home_menu_item channels_path, 'channels', 'Channels', 0
      .menu-row
        = home_menu_item '#', 'member_engagement', 'Member Engagement', 0
        = home_menu_item '#', 'chapter_performance', 'Chapter Performance', 0
        = home_menu_item organization_links_path, 'my_links', 'My Links', 0
        = home_menu_item budgets_path, 'expenses', 'Expenses', 0
        = home_menu_item dues_path, 'dues', 'Dues', 0
      .menu-row
        = home_menu_item '#', 'organizational_chart', 'Organizational Chart', 0
        = home_menu_item forms_path, 'forms', 'Forms', 0
        = home_menu_item meeting_notes_path, 'minutes', 'Minutes', 0
        = home_menu_item root_path, 'house_corporation', 'House Corporation', 0
        = home_menu_item points_transactions_path, 'points', 'Points', 0
      .menu-row
        = home_menu_item my_info_users_path, 'my_info', 'My Info', 0
        = home_menu_item birthdays_path, 'birthday', 'Birthday', 0
        = home_menu_item user_grades_path, 'scholarship', 'Scholarship', 0
        = home_menu_item teams_path, 'teams', 'Teams', 0
        = home_menu_item direct_messages_path, 'message', 'Message', current_user.unread_messages_count
        -#.menu-item
        -#  %span{style: 'display: block; width: 84px; content: "";'}


    = render_svg_sprite

app/views/static_pages/membership_engagement.html.haml
.page-container
  = svg_icon 'member_engagement'

app/views/static_pages/points.html.haml
.page-container
  = svg_icon 'dues'