config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  # API ROUTES ---------------------------------------------------

  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      post '/login',              to: 'sessions#create'
      post '/logout',             to: 'sessions#destroy'
      post '/reset_password',     to: 'users#reset_password'

      resources :users, only: [:index, :show, :update] do
        resources :tasks, only: [:index, :show, :create, :update] do
          post '/complete', to: 'tasks#complete', on: :member
          post '/incomplete', to: 'tasks#incomplete', on: :member
        end
        resources :points_transactions, only: [:index, :create]
      end

      resources :approvals, only: [:index] do
        post '/approve', to: 'approvals#approve', on: :member
      end

      resources :dues, only: [:index]
      resources :dues_transactions, only: [:index, :create]

      resources :event_invites, only: [:index] do
        post '/rsvp', to: 'event_invites#rsvp', on: :member
        post '/check_in', to: 'event_invites#check_in', on: :member
      end

      resources :meeting_notes, only: [:index, :show, :create]

      resources :channels, only: [:index] do
        resources :messages, only: [:index, :create]
      end

      resources :direct_messages, only: [:index, :create] do
        resources :message_groups_users, only: [:index, :create, :update]
        resources :messages, only: [:index, :create]
      end

      resources :budgets, only: [:index] do
        resources :budget_transactions, only: [:index, :create]
      end

      resources :user_grades, only: [:index, :show, :create]
    end
  end


  # WEB APP ROUTES ---------------------------------------------------

  root 'static_pages#index'
  get 'my_flow', to: 'users#my_flow'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }

  resources :users, only: [:index, :show] do
    collection do
      get 'my_info', action: :my_info
      put 'update_my_avatar', action: :update_my_avatar
      put 'update_my_info', action: :update_my_info
    end
  end

  resources :user_grades, only: [:index, :create, :destroy]

  resources :points_transactions, only: [:index, :create]

  resources :tasks, only: [:index, :create] do
    post '/complete', to: 'tasks#complete', on: :member
  end

  resources :calendar, only: [:index, :show, :new, :create] do
    member do
      post 'rsvp', action: :rsvp
      post 'invite', action: :invite
    end

    collection do
      post 'events', action: :events
      post 'event', action: :create_event
    end
  end

  resources :forms, only: [:index] do
    resources :form_submissions, only: [:index, :create]
  end

  resources :teams, only: [:index, :show, :create, :update, :destroy] do
    put 'update_organization_image', action: :update_organization_image, on: :member
    resources :organization_user_roles, only: [:create, :destroy]
  end

  resources :meeting_notes, only: [:index, :show]

  resources :channels, only: [:index, :show, :create, :destroy] do
    resources :messages, only: [:create]
  end

  resources :direct_messages, only: [:index, :show, :create, :destroy] do
    resources :messages, only: [:create]
  end

  resources :dues, only: [:index]
  resources :dues_transactions, only: [:create]

  resources :budgets, only: [:index, :show] do
    resources :budget_transactions, only: [:create]
  end

  resources :organization_links, only: [:index, :create, :destroy]

  resources :birthdays, only: [:index]

  resources :approvals, only: [:index] do
    post 'approve', action: :approve, on: :member
  end

  get 'st_page/:page', to: 'static_pages#page'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/budget.rb
class Budget < ApplicationRecord

	# ASSOCIATIONS ----------------------------------------------------------
	belongs_to 	:budgetable, 			polymorphic: true

	has_many 	:budget_transactions,	as: :transactable, dependent: :destroy
	has_many 	:approvals,				as: :approvable, dependent: :destroy

	# VALIDATIONS ----------------------------------------------------------
	validates :name, presence: true

	def subtract_from_remaining! amt
		self.remaining -= amt
		self.save
	end

	def total_spent
		budget_transactions.sum(:amount)
	end

end

app/controllers/api/v1/budgets_controller.rb
class Api::V1::BudgetsController < Api::ApiController
    before_action :authenticate_with_token!

	def index
		@budgets = current_user.budgets
	end

end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

	def index
		@budgets = current_user.budgets.uniq
	end

	def show
		@budget = Budget.find params[:id]

		unless current_user.budgets.include? @budget
			raise ActiveRecord::RecordNotFound
		end

		@user_can_view_transactions = current_user.can_view? BudgetTransaction

		if @user_can_view_transactions
			@expenses = @budget.budget_transactions
		else
			@expenses = current_user.expenses.where(transactable: @budget)
		end
	end

	private

    def set_controller_required_permissions
        @permissions_model = Budget
        @restricted_actions = [:create]
    end

end

app/views/budgets/index.html.haml
.container.white.full-height
  .grid-item.w-1_4.full-height
    %br
  .grid-item.w-2_4.full-height
    .table-container
      .table-title
        #{current_user.full_name}'s Budgets
      %table.table
        %thead
          %tr
            %th
              Type
            %th
              Type's Name
            %th
              Budget Name
            %th &nbsp;
        %tbody
          - @budgets.each do |budget|
            %tr
              %td
                = budget.budgetable_type
              %td
                = budget.budgetable.name
              %td
                = budget.name
              %td.link
                = link_to '>', budget_path(budget)

/     .table-title
/       Chapter Budget
/     %table.table

/       %tbody
/         %tr
/           %td
/             Oﬃcer Budgets:
/         %tr
/           %td
/             Chapter President
/         %tr
/           %td
/             Executive Vice President
/         %tr
/           %td
/             Membership Education Vice President
/         %tr
/           %td
/             Finance Vice President
/         %tr
/           %td
/             Recruitment & Marketing Vice President
/         %tr
/           %td
/             New Member Coordinator
/         %tr
/           %td
/             Formal Recruitment Chair
/         %tr
/           %td
/             Director of Standards and Ethics

/         %tr
/           %td
/             Director of Social Enrichment

/         %tr
/           %td
/             Philanthropy Chair
/         %tr
/           %td
/             Guard
/         %tr
/           %td
/             Panhellenic Delegate
/         %tr
/           %td
/             Scholarship Chair
/         %tr
/           %td
/             Alumnae Relations Chair
/         %tr
/           %td
/             Public Relations Chair
/         %tr
/           %td
/             Director of Standards and Ethics
/         %tr
/           %td
/             Director of Social Enrichment
/         %tr
/           %td
/             Philanthropy Chair
/         %tr
/           %td
/             Guard
/         %tr
/           %td
/             Executive Vice President
/         %tr
/           %td
/             Membership Education Vice President
/         %tr
/           %td
/             Finance Vice President
/         %tr
/           %td
/             Recruitment & Marketing Vice President
/         %tr
/           %td
/             New Member Coordinator
/         %tr
/           %td
/             Formal Recruitment Chair
/         %tr
/           %td
/             Director of Standards and Ethics

/         %tr
/           %td
/             Director of Social Enrichment

/         %tr
/           %td
/             Philanthropy Chair
/         %tr
/           %td
/             Guard
/         %tr
/           %td
/             Panhellenic Delegate
/         %tr
/           %td
/             Scholarship Chair
/         %tr
/           %td
/             Alumnae Relations Chair
/         %tr
/           %td
/             Public R
/         %tr
/           %td
/             Panhellenic Delegate
/         %tr
/           %td
/             Scholarship Chair
/         %tr
/           %td
/             Alumnae Relations Chair
/         %tr
/           %td
/             Public Relations Chair


/ .grid-item.w-2_4.full-height
/   .table-container.left-border
/     .table-title
/       Director of Social Enrichment Budget
/       %button.plus-btn{'data-modal-id': 'dse_budget_modal'}
/         +
/     %table.table
/       %thead
/         %tr
/           %th
/           %th
/       %tbody
/         %tr
/           %td Boat Cruise
/           %td $2,000.00
/         %tr
/           %td Semi-Formal
/           %td $1,000.00
/         %tr
/           %td Formal
/           %td $1,000.00
/         - 15.times do
/           %tr
/             %td
/             %td


/   .grid-item.w-1_4.full-height
/     .table-container.left-border
/       .table-title
/         Pending Reciepts
/         %button.plus-btn{'data-modal-id': 'pending_modal'}
/           +
/       %table.table
/         %thead
/           %tr
/             %th
/             %th
/         %tbody
/           %tr
/             %td Mallard Ball (2016)
/             %td >
/           %tr
/             %td Mixer (8/23/16)
/             %td >
/           %tr
/             %td Formal (2016)
/             %td >
/           - 15.times do
/             %tr
/               %td
/               %td


/ .modal-container#dse_budget_modal
/   .modal-window
/     Director of Social Enrichment Budget

/ .modal-container#pending_modal
/   .modal-window
/     Pending Reciepts

app/views/budgets/show.html.haml
.container.white
  .profile-wrapper.with-link

    = link_to ' BACK to Budgets', budgets_path, class: 'back-link'

    .table-container
      .table-title
        - if @user_can_view_transactions
          = "#{@budget.name} - Total: #{number_to_currency(@budget.total)}"
        - else
          #{current_user.full_name}'s Expenses
        %button.plus-btn{'data-modal-id': 'budget_transaction_modal'}
          +
      %table.table
        %thead
          %tr
            %th Created
            %th Created By
            %th Description
            %th &nbsp;
            %th Amount
        %tbody
          - @expenses.each do |expense|
            %tr
              %td.text-center
                = display_date(expense.created_at)
              %td
                = expense.created_by_user.full_name
              %td
                = expense.notes
              %td
                = display_attachment(expense.attachment)
              %td.text-center
                = number_to_currency(expense.amount)

        - if @user_can_view_transactions
          %tfoot
            %tr
              %td
                %strong Total Spent
              %td
              %td
              %td
              %td.text-center
                %strong= number_to_currency(@budget.total_spent)
            %tr.green
              %td
                %strong Remaining in Budget
              %td
              %td
              %td
              %td.text-center
                %strong= number_to_currency(@budget.remaining)

= render partial: 'application/modal/budget_transaction_modal'