config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  # API ROUTES ---------------------------------------------------

  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      post '/login',              to: 'sessions#create'
      post '/logout',             to: 'sessions#destroy'
      post '/reset_password',     to: 'users#reset_password'

      resources :users, only: [:index, :show, :update] do
        resources :tasks, only: [:index, :show, :create, :update] do
          post '/complete', to: 'tasks#complete', on: :member
          post '/incomplete', to: 'tasks#incomplete', on: :member
        end
        resources :points_transactions, only: [:index, :create]
      end

      resources :approvals, only: [:index] do
        post '/approve', to: 'approvals#approve', on: :member
      end

      resources :dues, only: [:index]
      resources :dues_transactions, only: [:index, :create]

      resources :event_invites, only: [:index] do
        post '/rsvp', to: 'event_invites#rsvp', on: :member
        post '/check_in', to: 'event_invites#check_in', on: :member
      end

      resources :meeting_notes, only: [:index, :show, :create]

      resources :channels, only: [:index] do
        resources :messages, only: [:index, :create]
      end

      resources :direct_messages, only: [:index, :create] do
        resources :message_groups_users, only: [:index, :create, :update]
        resources :messages, only: [:index, :create]
      end

      resources :budgets, only: [:index] do
        resources :budget_transactions, only: [:index, :create]
      end

      resources :user_grades, only: [:index, :show, :create]
    end
  end


  # WEB APP ROUTES ---------------------------------------------------

  root 'static_pages#index'
  get 'my_flow', to: 'users#my_flow'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }

  resources :users, only: [:index, :show] do
    collection do
      get 'my_info', action: :my_info
      put 'update_my_avatar', action: :update_my_avatar
      put 'update_my_info', action: :update_my_info
    end
  end

  resources :user_grades, only: [:index, :create, :destroy]

  resources :points_transactions, only: [:index, :create]

  resources :tasks, only: [:index, :create] do
    post '/complete', to: 'tasks#complete', on: :member
  end

  resources :calendar, only: [:index, :show, :new, :create] do
    member do
      post 'rsvp', action: :rsvp
      post 'invite', action: :invite
    end

    collection do
      post 'events', action: :events
      post 'event', action: :create_event
    end
  end

  resources :forms, only: [:index] do
    resources :form_submissions, only: [:index, :create]
  end

  resources :teams, only: [:index, :show, :create, :update, :destroy] do
    put 'update_organization_image', action: :update_organization_image, on: :member
    resources :organization_user_roles, only: [:create, :destroy]
  end

  resources :meeting_notes, only: [:index, :show]

  resources :channels, only: [:index, :show, :create, :destroy] do
    resources :messages, only: [:create]
  end

  resources :direct_messages, only: [:index, :show, :create, :destroy] do
    resources :messages, only: [:create]
  end

  resources :dues, only: [:index]
  resources :dues_transactions, only: [:create]

  resources :budgets, only: [:index, :show] do
    resources :budget_transactions, only: [:create]
  end

  resources :organization_links, only: [:index, :create, :destroy]

  resources :birthdays, only: [:index]

  resources :approvals, only: [:index] do
    post 'approve', action: :approve, on: :member
  end

  get 'st_page/:page', to: 'static_pages#page'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception
	respond_to :html

	before_action :authenticate_user!
	before_action :set_controller_required_permissions
	before_action :check_admin_role
	before_action :configure_permitted_parameters, if: :devise_controller?

	layout :set_layout

	def check_admin_role
		if user_signed_in? and current_user.permissions.include? 'admin'
			@admin = true
		end
	end

	rescue_from ActiveRecord::RecordNotFound do |exception|
		flash[:error] = exception.message
		redirect_back(fallback_location: root_path)
    end

	private

	def set_layout
		devise_controller? ? 'login' : 'application'
	end

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:account_update, keys: [:image])
	end


	################# PERMISSIONS #########################

    class PermissionsError < StandardError
    end

    rescue_from PermissionsError do |exception|
		flash[:error] = exception.message
		redirect_back(fallback_location: root_path)
    end

	def set_controller_required_permissions
		@permissions_model = nil
		@restricted_actions = []
	end

	before_action :current_user_can_create, only: [:create]
	def current_user_can_create
		if @permissions_model and @restricted_actions.include? :create
			unless current_user.can_create? @permissions_model
				raise PermissionsError.new("You do not have permission to create this #{@permissions_model.name}.");
			end
		end
	end

	before_action :current_user_can_view, only: [:show]
	def current_user_can_view
		if @permissions_model and @restricted_actions.include? :show
			unless current_user.can_view? @permissions_model
				raise PermissionsError.new("You do not have permission to view this #{@permissions_model.name}.");
			end
		end
	end

	before_action :current_user_can_edit, only: [:update]
	def current_user_can_edit
		if @permissions_model and @restricted_actions.include? :update
			unless current_user.can_edit? @permissions_model
				raise PermissionsError.new("You do not have permission to edit this #{@permissions_model.name}.");
			end
		end
	end

	before_action :current_user_can_delete, only: [:destroy]
	def current_user_can_delete
		if @permissions_model and @restricted_actions.include? :destroy
			unless current_user.can_delete? @permissions_model
				raise PermissionsError.new("You do not have permission to delete this #{@permissions_model.name}.");
			end
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def menu_item(path, svg_name, title, num_count, action = '')
    locals = {
        menu_item_path: path,
        svg_name: svg_name,
        title: title,
        num_count: num_count,
        actions: action.split(','),
    }
    render partial: 'menu_item', locals: locals
  end

  def display_date(date_object)
    if date_object.present?
      date_object.strftime('%_m/%_d/%y')
    else
      ''
    end
  end

  def display_attachment(attachment_object)
    if attachment_object.exists?
      return link_to attachment_object.url, target: :blank do
        svg_icon 'form_green'
      end
    else
      return svg_icon 'form_grey'
    end
  end

end

app/views/application/modal/_budget_modal.html.haml
.modal-container#budget_modal
  .modal-window
    .modal-header
      Budget
      %button.btn-close
        ✕
    .modal-body

app/views/application/modal/_budget_transaction_modal.html.haml
.modal-container#budget_transaction_modal
  .modal-window
    .modal-header
      Add Expense
      %button.btn-close
        ✕
    .modal-body
      = form_for [@budget, @budget.budget_transactions.build], multipart: true do |f|
        .form-input
          = f.label :amount
          = f.text_field :amount
        .form-input
          = f.label :notes
          = f.text_area :notes, cols: 20, rows: 10
        .form-input.date-select
          = f.label :occurred_at
          = f.datetime_select :occurred_at
        .form-input
          = f.label :attachment
          = f.file_field :attachment
        .form-submit{style: 'margin-top: 44px'}
          = f.submit "OK"

app/views/application/modal/_channel_modal.html.haml
.modal-container#channel_modal
  .modal-window
    .modal-header
      Create Channel
      %button.btn-close
        ✕
    .modal-body
      = form_for Channel.new do |f|
        .form-input
          = f.label :organization_id
          = f.collection_select :organization_id, current_user.organizations.uniq, :id, :name
        .form-input
          = f.label :name
          = f.text_field :name
        .form-submit{style: 'margin-top: 44px'}
          = f.submit

app/views/application/modal/_direct_message_modal.html.haml
.modal-container#direct_message_modal
  .modal-window
    .modal-header
      New Direct Message
      %button.btn-close
        ✕
    .modal-body
      = form_for DirectMessage.new(message_groups_users: [MessageGroupsUser.new]) do |f|
        .form-input
          = f.fields_for :message_groups_users do |mgu|
            = mgu.label :user_id
            = mgu.collection_select :user_id, current_user.my_directory, :id, :full_name
        .form-submit{style: 'margin-top: 44px'}
          = f.submit "OK"

app/views/application/modal/_dues_transaction_modal.html.haml
.modal-container#dues_transaction_modal
  .modal-window
    .modal-header
      Pay Dues
      %button.btn-close
        ✕
    .modal-body
      = form_for current_user.dues_transactions.build, multipart: true do |f|
        .form-input
          = f.label :amount
          = f.text_field :amount
        .form-input
          = f.label :notes
          = f.text_area :notes, cols: 20, rows: 10
        .form-input
          = f.label :attachment
          = f.file_field :attachment
        .form-submit{style: 'margin-top: 44px'}
          = f.submit "OK"

app/views/application/modal/_event_invite_modal.html.haml
.modal-container#event_invite_modal
  .modal-window
    .modal-header
      Invite to Event!
      %button.btn-close
        ✕
    .modal-body
      = form_for EventInvite.new, url: invite_calendar_path(@event) do |f|
        .form-input
          = f.label :user_id
          = f.collection_select :user_id, current_user.my_directory, :id, :full_name
        .form-submit{style: 'margin-top: 44px'}
          = f.submit "OK"

app/views/application/modal/_event_modal.html.haml
.modal-container#event_modal
  .modal-window
    .modal-header
      Event
      %button.btn-close
        ✕
    .modal-body
      = form_for Event.new, url: event_calendar_index_path do |f|
        .form-input
          = f.label :name
          = f.text_field :name
        .form-input
          = f.label :organization_id
          = f.collection_select :organization_id, current_user.organizations, :id, :name
        .form-input.date-select
          = f.label :occurs_at
          = f.datetime_select :occurs_at

        -#.form-input
        -#  = f.label :notes
        -#  = f.text_area :notes, cols: 20, rows: 10

        -#.form-input
        -#  = f.label :attachment
        -#  = f.file_field :attachment
        -#.form-submit{style: 'margin-top: 44px'}
        -#  = f.submit

        .form-submit{style: 'margin-top: 44px'}
          = f.submit 'OK'

      -#  :, :alcohol, :coordinator_id, :attachment

app/views/application/modal/_forms_modal.html.haml
.modal-container#forms_modal
  .modal-window
    .modal-header
      Forms
      %button.btn-close
        ✕
    .modal-body

app/views/application/modal/_organization_link_modal.html.haml
.modal-container#organization_link_modal
  .modal-window
    .modal-header
      Add Organization Link
      %button.btn-close
        ✕
    .modal-body
      = form_for OrganizationLink.new do |f|
        .form-input
          = f.label :organization_id
          = f.collection_select :organization_id, current_user.organizations.uniq, :id, :name
        .form-input
          = f.label :name
          = f.text_field :name
        .form-input
          = f.label :link
          = f.text_field :link
        .form-input
          = f.label :description
          = f.text_area :description, cols: 20, rows: 10
        .form-submit{style: 'margin-top: 44px'}
          = f.submit

app/views/application/modal/_points_transaction_modal.html.haml
.modal-container#points_transaction_modal
  .modal-window
    .modal-header
      Add Points
      %button.btn-close
        ✕
    .modal-body
      = form_for current_user.points_transactions.build, multipart: true do |f|
        .form-input
          = f.label :amount
          = f.text_field :amount
        .form-input
          = f.label :notes
          = f.text_area :notes, cols: 20, rows: 10
        .form-input
          = f.label :attachment
          = f.file_field :attachment
        .form-submit{style: 'margin-top: 44px'}
          = f.submit "OK"

app/views/application/modal/_task_modal.html.haml
.modal-container#task_modal
  .modal-window
    .modal-header
      Create new Task
      %button.btn-close
        ✕
    .modal-body
      = form_for current_user.tasks.build do |f|
        .form-input
          = f.label :assigned_to_user_id
          = f.collection_select :assigned_to_user_id, current_user.my_directory, :id, :full_name
        .form-input
          = f.label :notes
          = f.text_area :notes, cols: 20, rows: 10
        .form-input.date-select
          = f.label :due_at
          = f.datetime_select :due_at
        .form-input
          = f.label :attachment
          = f.file_field :attachment
        .form-submit{style: 'margin-top: 44px'}
          = f.submit

app/views/application/modal/_user_grade_modal.html.haml
.modal-container#user_grade_modal
  .modal-window
    .modal-header
      Create New Grade
      %button.btn-close
        ✕
    .modal-body
      = form_for current_user.user_grades.build do |f|
        .form-input
          = f.label :course
          = f.text_field :course
        .form-input
          = f.label :grade
          = f.text_field :grade
        .form-input
          = f.label :notes
          = f.text_area :notes, cols: 20, rows: 10
        .form-input
          = f.label :attachment
          = f.file_field :attachment
        .form-submit{style: 'margin-top: 44px'}
          = f.submit